
services:
  app:
    image: rolling_dices
    ports:
      - 3000:3000
    environment:
      MYSQL=HOST: mysql
      MYSQL_USER: root
      MYSQL_DB: rolling_dices
      MYSQL_PASSWORD: secret
  db:
    image: mysql
    ports:
      - 3306:3306
    volumes:
      - ./db:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=rolling_dices
      - MYSQL_ROOT_PASSWORD=secret