version: '3'
services:
  db:
    image: mysql:8.0
    container_name: nodejs_mysql
    environment:
      MYSQL_ROOT_PASSWORD: passprueba
      MYSQL_DATABASE: jocdaus
      MYSQL_USER: root
      MYSQL_PASSWORD: passprueba
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: